<?php
/**
 * @var Drobko\Storelocator\Block\StoreLocatorView $block
 * @var Drobko\Storelocator\Model\StoreLocator $store
 */

$store = $block->getStore();
?>
<div id="storeViewer">
    <div class="storeCard">

        <hr>
        <div class="storeInfo">
            <h1><?php echo $block->escapeHtml($store->getName()); ?></h1>
            <?php if ($store->getCity()): ?>
                <p><?php echo __('City') ?>: <?php echo $block->escapeHtml($store->getCity()); ?></p>
            <?php endif; ?>
            <?php if ($store->getZip()): ?>
                <p><?php echo __('Zip') ?>: <?php echo $block->escapeHtml($store->getZip()); ?></p>
            <?php endif; ?>
            <?php if ($store->getState()): ?>
                <p><?php echo __('State') ?>: <?php echo $block->escapeHtml($store->getState()); ?></p>
            <?php endif; ?>
            <?php if ($store->getAddress()): ?>
                <p><?php echo __('Address') ?>: <b><?php echo $block->escapeHtml($store->getAddress()); ?></b></p>
            <?php endif; ?>
            <p class="web"><a href="#">example.com</a></p>
            <p class="phone"><a href="tel:+14194220787">1 419-422-0787</a></p>
            <p class="mail"><a href="mailto:gallery@example.com">example@example.com</a></p>

        </div>

        <hr>
        <div class="storePhoto">
            <p><?php echo __('Store Photo') ?></p>
            <div> <img src="<?php echo $block->getStoreImageUrl($store); ?>"
                       alt="<?php echo $block->escapeHtml($store->getName()); ?>"></div>
        </div>
        <hr>

    </div>

    <div class="storeDescription">

        <div id="map"></div>

        <?php if ($store->getDescription()): ?>
            <p class="description"><?php echo $block->escapeHtml($store->getDescription()); ?></p>
        <?php endif; ?>

    </div>
</div>

<script type="text/x-magento-init">
{
  "#storeViewer": {
    "storeViewer": {
        "apiKey": "<?php echo $block->storeLocatorHelper->getStoreLocatorAPI(); ?>",
        "storeLat": <?php echo $store->getLatitude(); ?>,
        "storeLng": <?php echo $store->getLongitude(); ?>
    }
  }
}
</script>
