<?php
/**
 * @var Drobko\Storelocator\Block\StoreLocator $block
 * * @var Drobko\Storelocator\Model\StoreLocator $store
 */

$stores = $block->getStoresList();
$numPage = $block->getNumPage();
$pages = $block->getCountPages();

?>
<div id="storeLocator">
    <div class="storeList">

        <div class="search-box">
            <form method="post"
                  action="<?php echo $block->getPageUrl(1) ?>">
                <input type="search" id="searchStoreList" class="search" name="name_post" placeholder="Current location"
                       maxlength="128" value="<?php echo $block->getNameForSearch()?>">
                <div class="reset"><a href="<?= $block->resetSearch() ?>" >×</a></div>
                <button type="submit"><?php echo __("Search by name") ?></button>
            </form>

        </div>

        <ul id="storeList">
            <?php if ($stores): ?>
                <?php foreach ($stores as $store): ?>
                    <li class="storeCard"
                        data-storeId="<?php echo $block->escapeHtml($store->getId()); ?>"
                        data-link="<?php echo $block->getViewStore($store->getId()); ?>">

                        <img src="<?php echo $block->getStoreImageUrl($store); ?>"
                             alt="<?php echo $block->escapeHtml($store->getName()); ?>">

                        <div class="storeInfo">
                            <h1><?php echo $block->escapeHtml($store->getName()); ?></h1>
                            <?php if ($store->getCity()): ?>
                                <p><?php echo __('City') ?>: <?php echo $block->escapeHtml($store->getCity()); ?></p>
                            <?php endif; ?>
                            <?php if ($store->getZip()): ?>
                                <p><?php echo __('Zip') ?>: <?php echo $block->escapeHtml($store->getZip()); ?></p>
                            <?php endif; ?>
                            <?php if ($store->getState()): ?>
                                <p><?php echo __('State') ?>: <?php echo $block->escapeHtml($store->getState()); ?></p>
                            <?php endif; ?>
                            <?php if ($store->getAddress()): ?>
                                <p><?php echo __('Address') ?>
                                    : <?php echo $block->escapeHtml($store->getAddress()); ?></p>
                            <?php endif; ?>
                        </div>

                    </li>
                <?php endforeach; ?>
                <?php else:?>
                <h1>Not found</h1>
            <?php endif; ?>
        </ul>
        <div class="pagination">
            <?php if ($numPage != 1): ?>
                <a href="<?php echo $block->getPageUrl($numPage - 1) ?>"><</a>
            <?php endif; ?>
            <?php if ($pages != 1): ?>
                <?php for ($i = 1; $i <= $pages; $i++): ?>
                    <?php if ($i != $numPage): ?>
                        <a href="<?php echo $block->getPageUrl($i) ?>"><?php echo $i ?></a>
                    <?php else: ?>
                        <a class="active"><?php echo $i ?></a>
                    <?php endif ?>
                <?php endfor ?>
                <?php if (($numPage != $pages) && ($pages != 0)): ?>
                    <a href="<?= $block->getPageUrl($numPage + 1) ?>">></a>
                <?php endif; ?>
            <?php endif; ?>

        </div>

    </div>

    <div id="map"></div>
</div>

<script type="text/x-magento-init">
{
  "#storeLocator": {
    "storeLocator": {
        "apiKey": "<?php echo $block->storeLocatorHelper->getStoreLocatorAPI(); ?>",
        "stores": <?php echo json_encode($stores->getData()); ?>
    }
  }
}
</script>
